version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rental_room_db

  api:
    build:
      context: ./rentalroom-be
      dockerfile: Dockerfile
    volumes:
      - ./rentalroom-be:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    env_file:
      - ./rentalroom-be/.env.development
    depends_on:
      - postgres
      - redis
